name: Deploy to server with ssh
description: Deploy app in staging/prod server via ssh
inputs:
  ssh_user:
    description: User to connect to server
    required: true
  ssh_host:
    description: Host to connect to server
    required: true
  ssh_port:
    description: Port to connect to server
    required: false
    default: '22'
  ssh_key:
    description: ssh key to connect to server
    required: true
  repo_path:
    description: Path to repo
    required: true
  main_branch:
    description: Main branch to deploy
    required: false
    default: dev
  ssh_agent_sock:
    description: socket path for ssh-agent
    required: false
    default: /tmp/ssh_agent.sock
  script_name:
    description: Name of the script to execute
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Setup ssh config and ssh-agent
      run: |
        mkdir -p ~/.ssh/
        cat << EOF >  ~/.ssh/config
        Host staging
          HostName $SSH_HOST
          User $SSH_USER
          Port $SSH_PORT
          ForwardAgent yes
          StrictHostKeyChecking no
        EOF
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${SSH_KEY}"
      env:
        SSH_PORT: ${{ inputs.ssh_port }}
        SSH_HOST: ${{ inputs.ssh_host }}
        SSH_USER: ${{ inputs.ssh_user }}
        SSH_KEY: ${{ inputs.ssh_key }}
        SSH_AUTH_SOCK: ${{ inputs.ssh_agent_sock }}

  
    - name: Add know hosts
      run: |
        ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts
        ssh-keyscan github.com >> ~/.ssh/known_hosts
      shell: bash
      env:
        SSH_HOST: ${{ inputs.ssh_host }}

    - name: Pulling updates from repo
      run: |
        ssh staging 'cd "${REPO_PATH}" && git switch "${MAIN_BRANCH}" && git pull origin "${MAIN_BRANCH}"'
      shell: bash
      env:
        REPO_PATH: ${{ inputs.repo_path }}
        MAIN_BRANCH: ${{ inputs.main_branch }}

    - name: Deploy
      run: |
        ssh staging 'cd "${REPO_PATH}" && ./"${SCRIPT_NAME}"'
      env:
        SCRIP_NAME: ${{ inputs.script_name }}
