name: Continuous Deployment

on:
  push:
    branches:
      - master
      - dev

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: deploy
        uses: appleboy/ssh-action@master
        env:
          GITHUB_KEY: ${{ secrets.KEY }}
          CNT: ${{ github.repository }}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script_stop: true
          envs: GITHUB_KEY,CNT,SSH_AUTH_SOCK
          script: |
            echo "${GITHUB_KEY}" | ssh-add -
            cd /opt/test.actions
            ls -la
            echo "I am $FOO"
            echo "I am $BAR"
            echo "sha: $SHA" 
            echo "context: $CNT" 
            