name: Deploy on dev server

on: 
  push:
    branches:
      - dev

jobs:
  
  Deploy:
    runs-on: ubuntu-latest
    name: update server and deploy
    steps:
      - uses: actions/checkout@v2
      - id: deploy-action
        uses: ./.github/actions/deploy/
        with:
          ssh_key: ${{ secrets.KEY }}
          ssh_user: ${{ secrets.USERNAME }}
          ssh_port: ${{ secrets.PORT }}
          ssh_host: ${{ secrets.HOST }}
          repo_path: '/opt/test.actions'
    
