name: Continuous Deployment

on:
  push:
    branches:
      - master
      - dev

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: deploy
        uses: appleboy/ssh-action@master
        env:
          GITHUB_KEY: ${{ secrets.KEY }}
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script_stop: true
          script: |
            cd /opt/test.actions
            ls -la
            echo "key: $GITHUB_KEY"
            