name: Testing CD/CD with gitgub actions

on: 
  push:
    branches:
      - master
      - dev 

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Show info
        run: echo "Hello World"

  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    

      - name: Setup ssh agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.KEY }}

      - name: Pulling updates from repo
        env: 
          REPO: /opt/test.actions
        run: ssh -A -i ${{ secrets.KEY}} -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'cd ${{ env.REPO }} && git pull origin master'

      # - name: deploy
      #   uses: appleboy/ssh-action@master
      #   env:
      #     GITHUB_KEY: ${{ secrets.KEY }}
      #     CNT: ${{ github.repository }}
      #     SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      #   with:
      #     host: ${{ secrets.HOST }}
      #     port: ${{ secrets.PORT }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.KEY }}
      #     script_stop: true
      #     envs: GITHUB_KEY,CNT,SSH_AUTH_SOCK
      #     script: |
      #       export GITHUB_KEY="${GITHUB_KEY}"
      #       cd /opt/test.actions
      #       ./deploy.sh
