name: Testing CD/CD with gitgub actions

on: 
  push:
    branches:
      - master
      - dev 

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Show info
        run: echo "Hello World"
