name: Testing CD/CD with gitgub actions

on: 
  push:
    branches:
      - master
      - dev
env:
  SSH_KEY: ${{ secrets.KEY }}
  SSH_USER: ${{ secrets.USERNAME }}
  SSH_PORT: ${{ secrets.PORT }}
  SSH_HOST: ${{ secrets.HOST }}

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Show info
        run: echo "Hello World"

  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup ssh config
        run: |
          mkdir -p ~/.ssh/
          cat << EOF >  ~/.ssh/config
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            Port $SSH_PORT
            ForwardAgent yes
            StrictHostKeyChecking no
          EOF
    
      - name: Add know hosts
        run: |
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Pulling updates from repo
        env: 
          REPO: /opt/test.actions
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${SSH_KEY}"
          echo $SSH_AUTH_SOCK
          ls /tmp/ssh-*
          ssh staging 'cd /opt/test.actions && git pull origin master'

      - name: Deploy
        run: |
          ls /tmp/ssh-*
          ssh staging 'cd /opt/test.actions && ./deploy.sh'
