name: Testing CD/CD with gitgub actions

on: 
  push:
    branches:
      - master
      - dev 

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Show info
        run: echo "Hello World"

  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup ssh agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.KEY }}"
        # uses: webfactory/ssh-agent@v0.5.4
        # with:
        #   ssh-private-key: ${{ secrets.KEY }} 

      - name: Pulling updates from repo
        env: 
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          REPO: /opt/test.actions
        run: |
          echo "1. "
          ssh-add -l
          echo "2. "
          pwd
          ls ~/.ssh/
          cat ~/.ssh/*
          ssh -A -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'ls -la'
  
      # - name: deploy
      #   uses: appleboy/ssh-action@master
      #   env:
      #     GITHUB_KEY: ${{ secrets.KEY }}
      #     CNT: ${{ github.repository }}
      #     SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      #   with:
      #     host: ${{ secrets.HOST }}
      #     port: ${{ secrets.PORT }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.KEY }}
      #     script_stop: true
      #     envs: GITHUB_KEY,CNT,SSH_AUTH_SOCK
      #     script: |
      #       export GITHUB_KEY="${GITHUB_KEY}"
      #       cd /opt/test.actions
      #       ./deploy.sh
