name: Running build and tests

on: 
  pull_request:
    branches:
      - master
      - dev
  push:
    branches:
      - dev

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Show info
        run: echo "Hello World"

